#!/usr/bin/env python
# MIT License
#
# Copyright (c) 2025 Nathan G. Barguss - 2E0NBS
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

"""Generate a monolithic CHIRP driver for the Radtel RT-950 Pro."""
from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Callable, Iterable, List, Sequence

MODULE_ORDER: Sequence[tuple[str, Path, Callable[[str], str]]] = (
    ("channel", Path("rt950pro/channel.py"), None),
    ("sections", Path("rt950pro/sections.py"), None),
    ("settings_api", Path("rt950pro/settings_api.py"), None),
    ("image", Path("rt950pro/image.py"), None),
    ("transport", Path("rt950pro/transport.py"), None),
    ("driver", Path("rt950pro/chirp_driver.py"), None),
)

HEADER = """CHIRP driver for the Radtel RT-950 Pro (generated).

This file was generated by `scripts/build_monolith.py`. Do not edit manually;
update the generator or the source modules under `rt950pro/` instead.
"""

OUTPUT_PATH = Path("chirp_driver/radtel_rt950pro.py")


def _read_module(path: Path) -> str:
    """Return module text with Windows newlines normalised and BOM stripped."""
    text = path.read_text(encoding="utf-8-sig")
    return text.replace("\r\n", "\n")


def _strip_future_import(text: str) -> str:
    """Remove ``from __future__ import annotations`` regardless of location."""
    return re.sub(r"^from __future__ import annotations\s*\n", "", text, flags=re.MULTILINE)


def _extract_imports(text: str) -> tuple[str, List[str]]:
    """Split module text into (body, top-level import lines)."""
    imports: List[str] = []
    body_lines: List[str] = []
    lines = text.splitlines()
    idx = 0
    while idx < len(lines):
        line = lines[idx]
        stripped = line.strip()
        is_top_level = not line.startswith(" ") and not line.startswith("\t")
        if is_top_level and (stripped.startswith("import ") or stripped.startswith("from ")):
            imports.append(line)
            if stripped.endswith("("):
                idx += 1
                while idx < len(lines):
                    cont = lines[idx]
                    cont_stripped = cont.strip()
                    if cont_stripped.startswith(")"):
                        break
                    idx += 1
                idx += 1  # skip closing line
                continue
            idx += 1
            continue
        body_lines.append(line)
        idx += 1
    body = "\n".join(body_lines)
    return body, imports


def _remove_relative_imports(imports: Iterable[str]) -> List[str]:
    cleaned: List[str] = []
    skip_modules = {"typing", "dataclasses", "enum", "pathlib", "logging", "serial", "unicodedata", "random"}
    for line in imports:
        stripped = line.strip()
        if stripped.startswith("from .") or stripped.startswith("import ."):
            continue
        if stripped.startswith("from rt950pro"):
            continue
        if stripped.startswith("import "):
            module = stripped.split()[1].split('.')[0]
            if module in skip_modules:
                continue
        elif stripped.startswith("from "):
            module = stripped.split()[1].split('.')[0]
            if module in skip_modules:
                continue
        cleaned.append(line)
    return cleaned


def _transform_channel(text: str) -> str:
    text = text.replace("_LOG = get_logger(\"channel\")", "LOG = logging.getLogger(__name__ + \".channel\")")
    text = text.replace("_LOG", "LOG")
    return text


def _transform_image(text: str) -> str:
    text = text.replace("_CHANNEL_LOG = get_logger(\"image\")", "CHANNEL_LOG = logging.getLogger(__name__ + \".image\")")
    text = text.replace("_CHANNEL_LOG", "CHANNEL_LOG")
    return text


def _transform_transport(text: str) -> str:
    return text


def _transform_driver(text: str) -> str:
    return text


TRANSFORMERS: dict[str, Callable[[str], str]] = {
    "channel": _transform_channel,
    "image": _transform_image,
    "transport": _transform_transport,
    "driver": _transform_driver,
}


def _apply_transform(name: str, text: str) -> str:
    transformer = TRANSFORMERS.get(name)
    if transformer:
        return transformer(text)
    return text


def _normalise_whitespace(text: str) -> str:
    text = re.sub(r"\n{3,}", "\n\n", text)
    if not text.endswith("\n"):
        text += "\n"
    return text


def build_monolith(output_path: Path) -> None:
    module_bodies: List[str] = []
    extra_imports: List[str] = []

    for name, path, _ in MODULE_ORDER:
        module_text = _read_module(path)
        module_text = _strip_future_import(module_text)
        module_body, module_imports = _extract_imports(module_text)
        extra_imports.extend(_remove_relative_imports(module_imports))
        module_body = _apply_transform(name, module_body)
        module_bodies.append(module_body.strip())

    header = f"\"\"\"{HEADER.strip()}\"\"\"\n\n"

    required_imports = [
        "from __future__ import annotations",
        "import logging",
        "import random",
        "import unicodedata",
        "from dataclasses import dataclass, field",
        "from enum import Enum",
        "from pathlib import Path",
        "from typing import Dict, Iterable, List, Optional, Sequence, Tuple",
        "import serial",
    ]

    imports_block: List[str] = []
    seen: set[str] = set()
    for line in required_imports + extra_imports:
        if not line:
            continue
        stripped = line.strip()
        if stripped in seen:
            continue
        seen.add(stripped)
        imports_block.append(stripped)
    imports_block.append("")

    parts: List[str] = [header, "\n".join(imports_block)]

    for body in module_bodies:
        parts.append(body.strip())
        parts.append("\n\n")

    monolith = "".join(parts)
    monolith += '\n@directory.register\nclass RT950ProDriver(RT950ProRadio):\n    """Monolithic wrapper for RT-950 Pro."""\n    pass\n\nDRIVER_CLASS = RT950ProDriver\n'
    monolith = _normalise_whitespace(monolith)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(monolith, encoding="utf-8")
    print(f"Wrote {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help="Destination file for the generated driver",
    )
    args = parser.parse_args()
    build_monolith(args.output)


if __name__ == "__main__":
    main()
